name: Reward Citizen (Mint GRC)

on:
  workflow_dispatch:
    inputs:
      citizen:
        description: 'Citizen Wallet Address'
        required: true
        default: '0x02f92abad9F3bC0305BCe712bab26c26E19A36b1'
      amount:
        description: 'Amount of GRC'
        required: true
        default: '5'

jobs:
  mint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install ethers

      - name: Execute Minting
        env:
          ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
          CITIZEN_ADDRESS: ${{ github.event.inputs.citizen }}
          AMOUNT: ${{ github.event.inputs.amount }}
        run: node mint.js
